name: CI

on:
  push:
    branches: [ main ]


jobs:

  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: quay.io/grokspawn/cool-catalog
          tags: ${{ github.event.number }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: . 
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: catalog.Dockerfile

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: catalog.Dockerfile
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.QUAY_PASSWORD }}
