name: CI

on:
  push:
    branches: [ main ]


jobs:

  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: login to registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: grokspawn/cool-catalog
          tags: ${{ github.event.number }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: . 
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: catalog.Dockerfile

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: catalog.Dockerfile
