name: CI

on:
  pull_request:
    branches: 
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
  
      # models a future action where the submittor is validated against auth access for the
      # catalog contribution
    - name: Validate Contributor
      run: |
        grep -c ${{ github.actor }} CODEOWNERS

    - name: Validate Contribution
      uses: joelanford/opm-validate@main
      with:
        catalog: catalog

