name: CI

on:
  pull_request:
    branches: 
    - '**'

jobs:

  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
  
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@3
        with:
          images: quay.io/grokspawn/cool-catalog
          tags: ${{ github.event.number }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: catalog.Dockerfile
          context: . 

  validate:
    runs-on: quay.io/operator-framework/opm:latest
    steps:
      - uses: actions/checkout@v2
      - run: opm validate $GITHUB_WORKSPACE/catalog/
