name: CI

on:
  pull_request:
    branches: 
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
  
      # models a future action where the submittor is validated against auth access for the
      # catalog contribution
      - name: Validate Contributor
        run: |
          NUM_OWNERS=`grep -c ${{ github.actor }} CODEOWNERS`
          if [ $NUM_OWNER -eq 0 ] ; then
            exit 1
          fi

      - name: Validate Contribution
        uses: joelanford/opm-validate@main
        with:
          catalog: catalog

